In [1]:
import pandas as pd
import numpy as np

## 1. Understand the Problem (MOST IMPORTANT)

## Before touching data:

### Q. What is the target variable?
Is it:
- Regression → continuous (e.g., price)
- Classification → categorical (e.g., failure / no failure)
### Q. What is the business goal?
### Q. What metric matters?
- Accuracy / F1 / RMSE / MAE

👉 Example:

1. Predict machine failure → Classification
2. Predict sales → Regression

In [2]:
df = pd.read_csv('Bengaluru_House_Data.csv')
df.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [3]:
df.shape

(13320, 9)

# 1) Data Understanding

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [5]:
df['area_type'].value_counts()

area_type
Super built-up  Area    8790
Built-up  Area          2418
Plot  Area              2025
Carpet  Area              87
Name: count, dtype: int64

In [6]:
df['availability'].value_counts()

availability
Ready To Move    10581
18-Dec             307
18-May             295
18-Apr             271
18-Aug             200
                 ...
15-Aug               1
17-Jan               1
16-Nov               1
16-Jan               1
14-Jul               1
Name: count, Length: 81, dtype: int64

In [7]:
df['location'].value_counts()

location
Whitefield                        540
Sarjapur  Road                    399
Electronic City                   302
Kanakpura Road                    273
Thanisandra                       234
                                 ...
Bapuji Layout                       1
1st Stage Radha Krishna Layout      1
BEML Layout 5th stage               1
singapura paradise                  1
Abshot Layout                       1
Name: count, Length: 1305, dtype: int64

In [8]:
df['size'].value_counts()

size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
11 Bedroom       2
10 BHK           2
14 BHK           1
13 BHK           1
12 Bedroom       1
27 BHK           1
43 Bedroom       1
16 BHK           1
19 BHK           1
18 Bedroom       1
Name: count, dtype: int64

In [9]:
df['total_sqft'].value_counts()

total_sqft
1200    843
1100    221
1500    205
2400    196
600     180
       ...
3580      1
2461      1
1437      1
2155      1
4689      1
Name: count, Length: 2117, dtype: int64

In [10]:
df['bath'].value_counts()

bath
2.0     6908
3.0     3286
4.0     1226
1.0      788
5.0      524
6.0      273
7.0      102
8.0       64
9.0       43
10.0      13
12.0       7
13.0       3
11.0       3
16.0       2
27.0       1
40.0       1
15.0       1
14.0       1
18.0       1
Name: count, dtype: int64

In [11]:
df['balcony'].value_counts()

balcony
2.0    5113
1.0    4897
3.0    1672
0.0    1029
Name: count, dtype: int64

In [12]:
df['price'].value_counts()

price
75.00     310
65.00     302
55.00     275
60.00     270
45.00     240
         ...
351.00      1
54.10       1
80.64       1
32.73       1
488.00      1
Name: count, Length: 1994, dtype: int64

#### Null Values

In [13]:
df.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

#### Best to Drop irrelevent columns at first

In [14]:
df = df.drop(['availability', 'society','area_type','balcony'], axis=1)

# 3. Data Cleaning

In [15]:
df.head()

                   location       size total_sqft  bath   price
0  Electronic City Phase II      2 BHK       1056   2.0   39.07
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00
2               Uttarahalli      3 BHK       1440   2.0   62.00
3        Lingadheeranahalli      3 BHK       1521   3.0   95.00
4                  Kothanur      2 BHK       1200   2.0   51.00

In [16]:
df.describe()

               bath         price
count  13247.000000  13320.000000
mean       2.692610    112.565627
std        1.341458    148.971674
min        1.000000      8.000000
25%        2.000000     50.000000
50%        2.000000     72.000000
75%        3.000000    120.000000
max       40.000000   3600.000000

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13319 non-null  object
 1   size        13304 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13247 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB

## Handle Missing Values

In [18]:
df.isnull().sum()

location       1
size          16
total_sqft     0
bath          73
price          0
dtype: int64

In [19]:
df['location'].value_counts()

location
Whitefield                        540
Sarjapur  Road                    399
Electronic City                   302
Kanakpura Road                    273
Thanisandra                       234
                                 ...
Bapuji Layout                       1
1st Stage Radha Krishna Layout      1
BEML Layout 5th stage               1
singapura paradise                  1
Abshot Layout                       1
Name: count, Length: 1305, dtype: int64

In [20]:
df['location'] = df['location'].fillna('Sarjapur  Road')

In [21]:
df['size'].value_counts()

size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
11 Bedroom       2
10 BHK           2
14 BHK           1
13 BHK           1
12 Bedroom       1
27 BHK           1
43 Bedroom       1
16 BHK           1
19 BHK           1
18 Bedroom       1
Name: count, dtype: int64

In [22]:
df['size'] = df['size'].fillna('2 BHK')

In [23]:
df['bath'] = df['bath'].fillna(df['bath'].median)

In [24]:
df.isnull().sum()

location      0
size          0
total_sqft    0
bath          0
price         0
dtype: int64

In [25]:
df['bhk'] = df['size'].str.split().str[0].astype(int)

In [26]:
df.drop('size', axis=1, inplace=True)

In [27]:
df[df['bhk'] > 20]                                         # outliers

                       location total_sqft  bath  price  bhk
1718  2Electronic City Phase II       8000  27.0  230.0   27
4684                Munnekollal       2400  40.0  660.0   43

In [28]:
df['total_sqft'].unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      shape=(2117,), dtype=object)

In [29]:
def convert_sqft(x):
    x = str(x)
    if '-' in x:
        a, b = x.split('-')
        return (float(a) + float(b)) / 2
    try:
        return float(x)
    except:
        return None                                # for nan

In [30]:
df['total_sqft'] = df['total_sqft'].apply(convert_sqft)                     # applying fun on df['total_sqft'] for every row value

In [31]:
df.head()

                   location  total_sqft bath   price  bhk
0  Electronic City Phase II      1056.0  2.0   39.07    2
1          Chikka Tirupathi      2600.0  5.0  120.00    4
2               Uttarahalli      1440.0  2.0   62.00    3
3        Lingadheeranahalli      1521.0  3.0   95.00    3
4                  Kothanur      1200.0  2.0   51.00    2

## 4. Feature Engineering

In [32]:
df['price_per_sqft'] = df['price'] * 100000 / df['total_sqft']                   # price in lakhs

In [33]:
df.head()

                   location  total_sqft bath   price  bhk  price_per_sqft
0  Electronic City Phase II      1056.0  2.0   39.07    2     3699.810606
1          Chikka Tirupathi      2600.0  5.0  120.00    4     4615.384615
2               Uttarahalli      1440.0  2.0   62.00    3     4305.555556
3        Lingadheeranahalli      1521.0  3.0   95.00    3     6245.890861
4                  Kothanur      1200.0  2.0   51.00    2     4250.000000

In [34]:
df.describe().round()

       total_sqft    price      bhk  price_per_sqft
count     13274.0  13320.0  13320.0         13274.0
mean       1560.0    113.0      3.0          7908.0
std        1238.0    149.0      1.0        106430.0
min           1.0      8.0      1.0           268.0
25%        1100.0     50.0      2.0          4267.0
50%        1276.0     72.0      3.0          5434.0
75%        1680.0    120.0      3.0          7312.0
max       52272.0   3600.0     43.0      12000000.0

In [35]:
df['location'].value_counts()

location
Whitefield                        540
Sarjapur  Road                    400
Electronic City                   302
Kanakpura Road                    273
Thanisandra                       234
                                 ...
Bapuji Layout                       1
1st Stage Radha Krishna Layout      1
BEML Layout 5th stage               1
singapura paradise                  1
Abshot Layout                       1
Name: count, Length: 1305, dtype: int64

In [36]:
location_counts = df['location'].value_counts()

In [37]:
rare_locations = location_counts[location_counts <= 10]
print(rare_locations)

location
Kalkere                           10
Gunjur Palya                      10
Dodsworth Layout                  10
BTM 1st Stage                     10
Sadashiva Nagar                   10
                                  ..
Bapuji Layout                      1
1st Stage Radha Krishna Layout     1
BEML Layout 5th stage              1
singapura paradise                 1
Abshot Layout                      1
Name: count, Length: 1064, dtype: int64

In [38]:
df['location'] = df['location'].apply(lambda x: x if location_counts[x] > 10 else 'other')

In [39]:
df['location'].value_counts()

location
other                 2900
Whitefield             540
Sarjapur  Road         400
Electronic City        302
Kanakpura Road         273
                      ...
Marsur                  11
Banjara Layout          11
LB Shastri Nagar        11
Pattandur Agrahara      11
Narayanapura            11
Name: count, Length: 242, dtype: int64

## Remove Outliers

In [40]:
df.describe()

         total_sqft         price           bhk  price_per_sqft
count  13274.000000  13320.000000  13320.000000    1.327400e+04
mean    1559.626694    112.565627      2.802778    7.907501e+03
std     1238.405258    148.971674      1.294496    1.064296e+05
min        1.000000      8.000000      1.000000    2.678298e+02
25%     1100.000000     50.000000      2.000000    4.266865e+03
50%     1276.000000     72.000000      3.000000    5.434306e+03
75%     1680.000000    120.000000      3.000000    7.311746e+03
max    52272.000000   3600.000000     43.000000    1.200000e+07

- where do you find the 1 sq. fit flat?

## Total_sqft per BHK

In [41]:
(df['total_sqft']/df['bhk']).describe()

count    13274.000000
mean       575.074878
std        388.205175
min          0.250000
25%        473.333333
50%        552.500000
75%        625.000000
max      26136.000000
dtype: float64

In [42]:
df_sq_bh = df['total_sqft']/df['bhk']

In [43]:
df_sq_bh.describe()

count    13274.000000
mean       575.074878
std        388.205175
min          0.250000
25%        473.333333
50%        552.500000
75%        625.000000
max      26136.000000
dtype: float64

### we're keeping only those whose Total_sqft per BHK is greater than 300

In [44]:
df = df[df['total_sqft']/df['bhk'] > 300]

In [45]:
df.describe()

         total_sqft         price           bhk  price_per_sqft
count  12348.000000  12348.000000  12348.000000    12348.000000
mean    1601.084689    110.823169      2.633301     6207.869136
std     1268.788019    152.794399      0.964402     4047.666274
min      340.000000      8.440000      1.000000      267.829813
25%     1115.000000     49.000000      2.000000     4200.000000
50%     1305.000000     69.475000      3.000000     5264.632169
75%     1708.000000    115.000000      3.000000     6825.108836
max    52272.000000   3600.000000     16.000000   176470.588235

In [46]:
def remove_outliers(df):
    df_out = pd.DataFrame()
    for key, subdf in df.groupby('location'):
        mean = subdf['price_per_sqft'].mean()
        std = subdf['price_per_sqft'].std()
        reduced = subdf[
            (subdf['price_per_sqft'] > mean - std) &
            (subdf['price_per_sqft'] < mean + std)
        ]
        df_out = pd.concat([df_out, reduced], ignore_index=True)
    return df_out

In [47]:
df = remove_outliers(df)

In [48]:
df.describe()

         total_sqft         price           bhk  price_per_sqft
count  10120.000000  10120.000000  10120.000000    10120.000000
mean    1509.247723     91.005300      2.562451     5627.357994
std      881.359927     86.507174      0.880021     2212.625165
min      350.000000     10.000000      1.000000     1250.000000
25%     1110.000000     49.000000      2.000000     4242.424242
50%     1290.000000     67.000000      2.000000     5166.666667
75%     1650.000000    100.000000      3.000000     6399.131271
max    30400.000000   2200.000000     16.000000    24509.803922

In [49]:
def remove_bhk_outliers(df):
    df_out = pd.DataFrame()

    for loc, loc_df in df.groupby('location'):
        bhk_stats = {}

        # calculate mean price_per_sqft for each BHK
        for bhk, bhk_df in loc_df.groupby('bhk'):
            bhk_stats[bhk] = bhk_df['price_per_sqft'].mean()

        temp_df = pd.DataFrame()

        for bhk, bhk_df in loc_df.groupby('bhk'):
            if bhk - 1 in bhk_stats:
                # compare with previous BHK
                if bhk_stats[bhk] < bhk_stats[bhk - 1]:
                    continue  # remove this BHK group
            temp_df = pd.concat([temp_df, bhk_df])

        df_out = pd.concat([df_out, temp_df])

    return df_out

In [50]:
df = remove_bhk_outliers(df)

In [51]:
df.describe()

         total_sqft        price          bhk  price_per_sqft
count   6787.000000  6787.000000  6787.000000     6787.000000
mean    1581.386249   100.094881     2.645057     5876.281663
std      975.635654    97.217335     0.934957     2365.088363
min      350.000000    10.000000     1.000000     1250.000000
25%     1140.000000    51.000000     2.000000     4375.000000
50%     1375.000000    74.160000     3.000000     5409.309791
75%     1750.000000   113.095000     3.000000     6672.097012
max    30400.000000  2200.000000    16.000000    24509.803922

In [52]:
df

                   location  total_sqft  bath  price  bhk  price_per_sqft
1       Devarachikkanahalli      1250.0   2.0   40.0    2     3200.000000
2       Devarachikkanahalli      1200.0   2.0   83.0    2     6916.666667
3       Devarachikkanahalli      1170.0   2.0   40.0    2     3418.803419
5       Devarachikkanahalli       947.0   2.0   43.0    2     4540.654699
6       Devarachikkanahalli      1130.0   2.0   36.0    2     3185.840708
...                     ...         ...   ...    ...  ...             ...
10093                 other      4600.0   9.0  150.0    9     3260.869565
7946                  other      5000.0   9.0  360.0   11     7200.000000
9206                  other      6000.0  12.0  150.0   11     2500.000000
9533                  other      5425.0  13.0  275.0   13     5069.124424
8487                  other     10000.0  16.0  550.0   16     5500.000000

[6787 rows x 6 columns]

In [53]:
df.drop(columns = 'price_per_sqft', axis = 1, inplace = True)

## Cleaned Data

In [54]:
df.head()

               location  total_sqft bath  price  bhk
1   Devarachikkanahalli      1250.0  2.0   40.0    2
2   Devarachikkanahalli      1200.0  2.0   83.0    2
3   Devarachikkanahalli      1170.0  2.0   40.0    2
5   Devarachikkanahalli       947.0  2.0   43.0    2
6   Devarachikkanahalli      1130.0  2.0   36.0    2

In [55]:
df.to_csv('cleaned_data.csv')

## Training Preparation

In [56]:
X = df.drop(columns = 'price', axis = 1)

In [57]:
y = df['price']

## One hot encoding

In [58]:
df = pd.get_dummies(df, columns=['location'], drop_first=True,dtype=int)

In [59]:
df.head()

,total_sqft,bath,price,bhk,location_1st Block Jayanagar,location_1st Phase JP Nagar,location_2nd Phase Judicial Layout,location_2nd Stage Nagarbhavi,location_5th Block Hbr Layout,location_5th Phase JP Nagar,...,location_Vishveshwarya Layout,location_Vishwapriya Layout,location_Vittasandra,location_Whitefield,location_Yelachenahalli,location_Yelahanka,location_Yelahanka New Town,location_Yelenahalli,location_Yeshwanthpur,location_other
1,1250.0,2.0,40.0,2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1200.0,2.0,83.0,2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1170.0,2.0,40.0,2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,947.0,2.0,43.0,2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,1130.0,2.0,36.0,2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [60]:
df['bath'] = pd.to_numeric(df['bath'], errors='coerce')

In [61]:
df['bath'] = df['bath'].fillna(df['bath'].median())

In [62]:
from sklearn.model_selection import train_test_split

X = df.drop('price', axis=1)
y = df['price']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [63]:
X_train.shape

(5429, 244)

In [64]:
y_train.shape

(5429,)

In [65]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [66]:
from sklearn.metrics import r2_score, mean_absolute_error

y_pred = model.predict(X_test)

print("R2:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))

R2: 0.8800715642953605
MAE: 21.52142539542377

In [67]:
from sklearn.linear_model import Ridge

ridge_regression = Ridge(alpha = 1.0)                    # the 'Lamda' hyperparameter is alpha here.
ridge_regression.fit(X_train, y_train)

Ridge()

In [68]:
ridge_pred = ridge_regression.predict(X_test)

print("R2:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, ridge_pred))

R2: 0.8800715642953605
MAE: 21.595327709944037

In [69]:
from sklearn.linear_model import Lasso

lasso_regression = Lasso(alpha = 1.0)                    # the 'Lamda' hyperparameter is alpha here.
lasso_regression.fit(X_train, y_train)

Lasso()

In [70]:
lasso_pred = lasso_regression.predict(X_test)

print("R2:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, lasso_pred))

R2: 0.8800715642953605
MAE: 29.07094803451283

In [71]:
from sklearn.ensemble import RandomForestRegressor

rfr = RandomForestRegressor()
rfr.fit(X_train, y_train)

RandomForestRegressor()

In [72]:
rfr_pred = rfr.predict(X_test)

print("R2:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, rfr_pred))

R2: 0.8800715642953605
MAE: 19.560555418006658

- MAE: 19
- means better prediction accuracy

In [73]:
import pickle

In [74]:
pickle.dump(rfr, open('model.pkl','wb'))

In [75]:
pickle.dump(X.columns, open("columns.pkl", "wb"))